[build]
  base = "site"
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/hip/hip-:number"
  to = "/hip/hip-:number.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
