name: Dispatch Status Change Notifications (discord and email)
permissions:
    contents: read
    actions: write
on:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  DispatchNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      
      - name: Get status changes and hipnames then dispatch jobs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            arrayOfFiles=()
            while IFS= read -r; do
                arrayOfFiles+=("${REPLY}")
            done < <(git diff HEAD~1..HEAD -G'status:' --name-only | grep .md)
            arrayOfStatuses=()
            while IFS= read -r; do
                arrayOfStatuses+=("${REPLY}")
            done < <(git diff HEAD~1..HEAD -G'status:' | egrep "^\+status:" | cut -d ":" -f2)

            for ((i=0; i<${#arrayOfFiles[@]}; i++)); do
              echo "Initiating Discord workflow"
              gh workflow run send-discord-message.yml -f "filename=$(basename ${arrayOfFiles[$i]} .md)" -f "status=${arrayOfStatuses[$i]}"

              if [[ ${arrayOfStatuses[$i]} == " Last Call" ]]; then
                echo "Initiating Last Call workflow"
                gh workflow run send-email.yml -f "filename=$(basename ${arrayOfFiles[$i]} .md)" -f "status=Last Call"
              fi
            done