name: Send status email
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true
permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Send mail
        uses: step-security/action-send-mail@7238bab69680f644f9eab409cec92179d1d2f0ce # v6.0.1
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: hips@hedera.com
          password: ${{ secrets.GOOGLE_APP_PASS }}
          subject: ${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }}
          to: ${{ secrets.LAST_CALL_EMAILS }}
          from: The HIPs repository
          body: This is an automated message, please do not reply. Check https://hips.hedera.com/hip/${{ github.event.inputs.filename }} for more info. Thank you.
          secure: true
          priority: medium