name: Send discord notification
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: step-security/action-discord@b4bb54a2ec8218130ee588d2ca1fa358cf828735 # v0.1.2
        with:
          args:  "${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }} status https://hips.hedera.com/hip/${{ github.event.inputs.filename }}"