name: Send discord notification
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Extract HIP abstract
        id: extract_abstract
        run: |
          HIP_FILE="HIP/${{ github.event.inputs.filename }}"

          # Extract the abstract section (text between "## Abstract" and the next "##" heading)
          ABSTRACT=$(sed -n '/^## Abstract$/,/^## /p' "$HIP_FILE" | sed '$d' | tail -n +2 | sed '/^$/d')

          # If abstract is empty, use a default message
          if [ -z "$ABSTRACT" ]; then
            ABSTRACT="No abstract available for this HIP."
          fi

          # Save the abstract to output (escape for GitHub Actions)
          {
            echo "abstract<<EOF"
            echo "$ABSTRACT"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD }}
        uses: step-security/action-discord@25f3b8e2229f3a238679abdbcf82d84a075419bd # v0.1.3
        with:
          args: |
            # ${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }} status

            ## About this HIP
            ${{ steps.extract_abstract.outputs.abstract }}

            Read the full HIP here:
            https://hips.hedera.com/hip/${{ github.event.inputs.filename }}