name: Send status email
on:
  workflow_dispatch:
     inputs:
       filename:
         description: "Filename"
         type: string
         required: true
       status:
         description: "Status"
         type: string
         required: true
permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  StatusChangeNotifications:
    runs-on: hiero-improvement-proposals-linux-medium
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Send mail
        uses: step-security/action-send-mail@a995831af980a0a14953f75efec85509f5315e25 # v3.12.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: hips@hedera.com
          password: ${{ secrets.GOOGLE_APP_PASS }}
          subject: ${{ github.event.inputs.filename }} moved into ${{ github.event.inputs.status }}
          to: ${{ secrets.LAST_CALL_EMAILS }}
          from: The HIPs repository
          body: This is an automated message, please do not reply. Check https://hips.hedera.com/hip/${{ github.event.inputs.filename }} for more info. Thank you.
          secure: true
          priority: medium